#!/usr/bin/env bash
# a script that installs HAProxy & makes configurations to meet the following requirements:

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5517-web
    bind *:80
    mode http
    balance roundrobin
    server 5517-web-01 3.80.117.30:80 check
    server 5517-web-02 54.227.173.17:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
