#!/usr/bin/env bash
# Changes port 80 to 8080 in /etc/nginx/sites-available/default
# Bash script with the minimum number of commands to automate your fix

#!/usr/bin/env bash
# bash script that configures 'nginx' to run & listen to port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
