#!/usr/bin/env bash
# Update package repositories and install Nginx
apt-get update
apt-get install -y nginx

# Create necessary directories and files
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html

# Configure Nginx
sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
        return 301 http://youtube.com/;
    }
}
" > /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
