#!/usr/bin/env bash
# a Bash script containing commands
# Install Nginx web server
wget -qO - https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
echo "deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
sudo apt-get update
sudo apt-get install nginx -y

# Create a new configuration file for the redirection
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirect.conf
server {
  listen 80;
  server_name longmaker.tech;

  location /redirect_me {
    return 301 https://longmaker.tech/;
  }
}
EOF'

# Enable the new configuration file
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo systemctl restart nginx
