#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page;

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html


echo "Holberton School" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html


# Create custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/404.html >/dev/nullservice nginx restart

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me{
        return 301 http://youtube.com/;
     }
     error_page 404 /404.html;
     location /404 {
        root /etc/nginx/html;
        internal;
     }
}
" > /etc/nginx/sites-available/default
service nginx restart
